name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./002.OS_Template

    steps:
    - uses: actions/checkout@main

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '4.8-2013-q4' # <-- The compiler release to use

    - run: |
            export C_INCLUDE_PATH=/home/runner/gcc-arm-none-eabi-4_8-2013q4/lib/gcc/arm-none-eabi/4.8.1/include | 
            export CPLUS_INCLUDE_PATH=/home/runner/gcc-arm-none-eabi-4_8-2013q4/lib/gcc/arm-none-eabi/4.8.1/include |
            export LIBRARY_PATH=/home/runner/gcc-arm-none-eabi-4_8-2013q4/lib/gcc/arm-none-eabi/4.8.1 |
            mkdir output

    - name: build start
      run: make all
      working-directory: ${{ env.working-directory }}